// File generated by FlutterFire CLI and extended for multi-flavor support.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:simple_aac/flavors.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        switch (F.appFlavor) {
          case Flavor.dev:
            return iosDev;
          case Flavor.uat:
            return iosUat;
          case Flavor.prod:
          case Flavor.web:
          case null:
            return iosProd;
        }
      case TargetPlatform.android:
        switch (F.appFlavor) {
          case Flavor.dev:
            return androidDev;
          case Flavor.uat:
            return androidUat;
          case Flavor.prod:
          case Flavor.web:
          case null:
            return androidProd;
        }
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Web ────────────────────────────────────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM74_g5TwPiJ5ZoTeqxwPSbPnbf7dfyWk',
    appId: '1:997985384352:web:c8d66d53bf3710fee956c5',
    messagingSenderId: '997985384352',
    projectId: 'simpleaac-460e6',
    authDomain: 'simpleaac-460e6.firebaseapp.com',
    databaseURL: 'https://simpleaac-460e6.firebaseio.com',
    storageBucket: 'simpleaac-460e6.appspot.com',
    clientId: '997985384352-02mb3cdet5u3uoljhr4jmj7i9al610sd.apps.googleusercontent.com',
  );

  // ─── iOS ────────────────────────────────────────────────────────────────────

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyCxVlQSXwse9EE9i8jURkH0d-a_PRo5gzo',
    appId: '1:997985384352:ios:e85c68514d01bb20e956c5',
    messagingSenderId: '997985384352',
    projectId: 'simpleaac-460e6',
    authDomain: 'simpleaac-460e6.firebaseapp.com',
    databaseURL: 'https://simpleaac-460e6.firebaseio.com',
    storageBucket: 'simpleaac-460e6.appspot.com',
    iosBundleId: 'com.sealstudios.simpleaac.dev',
  );

  static const FirebaseOptions iosUat = FirebaseOptions(
    apiKey: 'AIzaSyCxVlQSXwse9EE9i8jURkH0d-a_PRo5gzo',
    appId: '1:997985384352:ios:5f5bde12086d293be956c5',
    messagingSenderId: '997985384352',
    projectId: 'simpleaac-460e6',
    authDomain: 'simpleaac-460e6.firebaseapp.com',
    databaseURL: 'https://simpleaac-460e6.firebaseio.com',
    storageBucket: 'simpleaac-460e6.appspot.com',
    iosBundleId: 'com.sealstudios.simpleaac.uat',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyCxVlQSXwse9EE9i8jURkH0d-a_PRo5gzo',
    appId: '1:997985384352:ios:94cb723559aadb76e956c5',
    messagingSenderId: '997985384352',
    projectId: 'simpleaac-460e6',
    authDomain: 'simpleaac-460e6.firebaseapp.com',
    databaseURL: 'https://simpleaac-460e6.firebaseio.com',
    storageBucket: 'simpleaac-460e6.appspot.com',
    iosBundleId: 'com.sealstudios.simpleaac.prod',
  );

  // ─── Android ────────────────────────────────────────────────────────────────

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyDmCr6eOqqXt41McT1I3g447yybMNCRSOM',
    appId: '1:997985384352:android:7e3c2549044f4cb7e956c5',
    messagingSenderId: '997985384352',
    projectId: 'simpleaac-460e6',
    authDomain: 'simpleaac-460e6.firebaseapp.com',
    databaseURL: 'https://simpleaac-460e6.firebaseio.com',
    storageBucket: 'simpleaac-460e6.appspot.com',
  );

  static const FirebaseOptions androidUat = FirebaseOptions(
    apiKey: 'AIzaSyDmCr6eOqqXt41McT1I3g447yybMNCRSOM',
    appId: '1:997985384352:android:3e6cb26322d31457e956c5',
    messagingSenderId: '997985384352',
    projectId: 'simpleaac-460e6',
    authDomain: 'simpleaac-460e6.firebaseapp.com',
    databaseURL: 'https://simpleaac-460e6.firebaseio.com',
    storageBucket: 'simpleaac-460e6.appspot.com',
  );

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyDmCr6eOqqXt41McT1I3g447yybMNCRSOM',
    appId: '1:997985384352:android:f8276f74d6d710cae956c5',
    messagingSenderId: '997985384352',
    projectId: 'simpleaac-460e6',
    authDomain: 'simpleaac-460e6.firebaseapp.com',
    databaseURL: 'https://simpleaac-460e6.firebaseio.com',
    storageBucket: 'simpleaac-460e6.appspot.com',
  );
}
