// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// On web, returns the web FirebaseOptions.
  /// On native platforms (Android/iOS), returns null — Firebase reads
  /// the bundled per-flavor google-services.json / GoogleService-Info.plist
  /// automatically, so no options need to be passed.
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) return web;
    return null;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM74_g5TwPiJ5ZoTeqxwPSbPnbf7dfyWk',
    appId: '1:997985384352:web:c8d66d53bf3710fee956c5',
    messagingSenderId: '997985384352',
    projectId: 'simpleaac-460e6',
    authDomain: 'simpleaac-460e6.firebaseapp.com',
    databaseURL: 'https://simpleaac-460e6.firebaseio.com',
    storageBucket: 'simpleaac-460e6.appspot.com',
  );

}
