name: Build and Deploy to Google Play

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  checks: write
  contents: read
  id-token: write
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.1
      - run: flutter --version
      - run: flutter pub get
      - name: Calculate Build Number
        run: |
          BUILD_NUMBER=$(( ${{ github.run_number }} + 100 ))
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
      - name: Build Prod Release
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m"
        run: flutter build appbundle --release -t lib/main_prod.dart --flavor prod --build-number=${{ env.BUILD_NUMBER }}
      - name: Upload to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: '${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_SECRET }}'
          packageName: com.sealstudios.simpleaac.prod
          releaseFiles: build/app/outputs/bundle/prodRelease/app-prod-release.aab
          track: internal
          inAppUpdatePriority: 1
          whatsNewDirectory: distribution/whatsnew
          mappingFile: build/app/outputs/mapping/prodRelease/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/prodRelease/mergeProdReleaseNativeLibs/out/lib
          changesNotSentForReview: ${{ vars.CHANGES_NOT_SENT_FOR_REVIEW }}
